import = ["/home/workboots/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 22.0

[font.bold]
family = "Inconsolata Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Inconsolata Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Inconsolata Nerd Font"
style = "Italic"

[font.normal]
family = "Inconsolata Nerd Font"
style = "Regular"

[window.padding]
x = 5
y = 1
